package pl.lasota.sensor.payload;

import lombok.Getter;

import java.util.List;

@Getter
public enum PayloadType {

    CONNECTED_ACK,

    PING,
    PING_ACK,

    CONFIG,
    CONFIG_ACK,


    PWM_WRITE_SET_UP,
    PWM_WRITE_SET_UP_ACK,
    PWM_WRITE_TEAR_DOWN,
    PWM_WRITE_TEAR_DOWN_ACK,
    PWM_WRITE_REQUEST,
    PWM_WRITE_RESPONSE,

    ANALOG_READ_SET_UP,
    ANALOG_READ_SET_UP_ACK,
    ANALOG_READ_TEAR_DOWN,
    ANALOG_READ_TEAR_DOWN_ACK,
    ANALOG_READ_ONE_SHOT_REQUEST,
    ANALOG_READ_ONE_SHOT_RESPONSE,
    ANALOG_READ_CONTINOUS_REQUEST,
    ANALOG_READ_CONTINOUS_RESPONSE,


    DIGITAL_SET_UP,
    DIGITAL_SET_UP_ACK,
    DIGITAL_TEAR_DOWN,
    DIGITAL_TEAR_DOWN_ACK,
    DIGITAL_WRITE_REQUEST,
    DIGITAL_WRITE_RESPONSE,
    DIGITAL_READ_ONE_SHOT_REQUEST,
    DIGITAL_READ_ONE_SHOT_RESPONSE,

    DIGITAL_READ_CONTINOUS_REQUEST,
    DIGITAL_READ_CONTINOUS_RESPONSE;


    public static List<PayloadType> getListMessageTypeFromDevice() {
        return List.of(CONNECTED_ACK, PING_ACK, CONFIG_ACK, PWM_WRITE_SET_UP_ACK, PWM_WRITE_TEAR_DOWN_ACK, PWM_WRITE_RESPONSE, ANALOG_READ_SET_UP_ACK,
                ANALOG_READ_TEAR_DOWN_ACK, ANALOG_READ_ONE_SHOT_RESPONSE, ANALOG_READ_CONTINOUS_RESPONSE, DIGITAL_SET_UP_ACK, DIGITAL_TEAR_DOWN_ACK, DIGITAL_WRITE_RESPONSE,
                DIGITAL_READ_ONE_SHOT_RESPONSE, DIGITAL_READ_CONTINOUS_RESPONSE);
    }


}
