eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  application:
    name: sensor-flows
  datasource:
    url: jdbc:postgresql://localhost:5432/sensor
    username: db
    password: db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false
  cloud:
    config:
      enabled: false
sensor:
  core:
    sensor-flows-name: sensor-flows
    firmware-folder: bin
server:
  port: 0