eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  application:
    name: sensor-api
  datasource:
    url: jdbc:postgresql://localhost:5432/sensor
    username: db
    password: db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false
  cloud:
    config:
      enabled: false

sensor:
  mqtt:
    client-id: ${random.uuid}
    url: tcp://127.0.0.1:1883
    topic: $share/mygroup/server
    username: mqttUserServer
    password: mqtt
    max-reconnect-delay: 5000
    connection-timeout: 30000
    automatic-reconnect: true
    unsecur-rest-endpoint: true
  core:
    sensor-flows-name: sensor-flows
    firmware-folder: bin
    jwt-internal:
      secret: Gkl3uP7ATJcLNka0p7+v4hY0OcTu9Y08+QP1sFYE4PI=
      expiration: 1440
server:
  port: 0