version: '3.8'
services:
  sensor-eclipse-mqtt:
    container_name: sensor-eclipse-mqtt-docker-compose
    build:
      context: ../
      dockerfile: docker/eclipse-mqtt.Dockerfile
    ports:
      - "1883:1883"
    networks:
      - internal-network
  sensor-postgres:
    container_name: sensor-postgres-docker-compose
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal-network
  sensor-app:
    container_name: sensor-app-docker-compose
    build:
      context: ../
      dockerfile: docker/sensor-app.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - internal-network
    depends_on:
      sensor-postgres:
        condition: service_started
  sensor-gui-frontend:
    container_name: sensor-frontend-docker-compose
    build:
      context: ../
      dockerfile: docker/sensor-gui-frontend.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - internal-network
    depends_on:
      sensor-app:
        condition: service_started
volumes:
  postgres-data:
    name: "sensor-postgres-docker-volume"
networks:
  internal-network:
    driver: bridge
