version: '3.8'
services:
  sensor-postgres:
    container_name: sensor-postgres-docker-compose
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal-network
  sensor-eureka:
    container_name: sensor-eureka-docker-compose
    build:
      context: ../
      dockerfile: docker/sensor-eureka.Dockerfile
    networks:
      - internal-network
  sensor-flows:
    container_name: sensor-flows-docker-compose
    build:
      context: ../
      dockerfile: docker/sensor-flows.Dockerfile
    networks:
      - internal-network
    depends_on:
      sensor-postgres:
        condition: service_started
      sensor-eureka:
        condition: service_started
  sensor-api:
    container_name: sensor-api-docker-compose
    build:
      context: ../
      dockerfile: docker/sensor-api.Dockerfile
    networks:
      - internal-network
    depends_on:
      sensor-postgres:
        condition: service_started
      sensor-eureka:
        condition: service_started
  sensor-gui-backend:
    container_name: sensor-backend-docker-compose
    build:
      context: ../
      dockerfile: docker/sensor-gui-backend.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - internal-network
    depends_on:
      sensor-postgres:
        condition: service_started
      sensor-eureka:
        condition: service_started
  sensor-gui-frontend:
    container_name: sensor-frontend-docker-compose
    build:
      context: ../
      dockerfile: docker/sensor-gui-frontend.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - internal-network
    depends_on:
      sensor-gui-backend:
        condition: service_started
volumes:
  postgres-data: { }
networks:
  internal-network:
    driver: bridge
