version: '3.9'
services:
  postgers:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=db
      - POSTGRES_USER=db
      - POSTGRES_DB=sensor
  volumes:
    - ~/apps/postgres:/var/lib/postgresql/data
  eureka:
    build: ../sensor-eureka
    ports:
      - "8761:8761"
  flows:
    build: ../sensor-flows
    environment:
      - PORT=0
    ports:
      - "0:0"
